{
 "title": "EPEver Tracer",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Solar Array Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Solar Array Power",
     "measurement": "PV_array_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /PV_Power|PV_array_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Energy Produced Today",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "Battery_charging_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_charging_power/)\r\n  |> integral(unit: 3600s)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Battery_voltage",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_voltage/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Solar Array Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Solar Array Voltage",
     "measurement": "PV_array_voltage",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /PV_array_voltage|PV_array_current/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    },
    {
     "alias": "Solar Array Current",
     "measurement": "PV_array_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Battery Charging Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Battery Charging Power",
     "measurement": "Battery_charging_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_charging_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Solar Array Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "PV_array_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /PV_array_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery Voltage",
     "measurement": "Battery_voltage",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_voltage|Battery_charging_current/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    },
    {
     "alias": "Barrery Charging Current",
     "measurement": "Battery_charging_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Load Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Load Power",
     "measurement": "Load_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Charging Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Battery_charging_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_charging_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Battery Temperature",
     "measurement": "Battery_temperature",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Battery_temperature|Internal_temperature/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    },
    {
     "alias": "Charger Temperature",
     "measurement": "Internal_temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Load Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Load Voltage",
     "measurement": "Load_voltage",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load_voltage|Load_current/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    },
    {
     "alias": "Load Current",
     "measurement": "Load_current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  },
  {
   "title": "Load Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Load_power",
     "query": "from(bucket: \"EPEver\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> last()\r\n  |> filter(fn: (r) => r[\"_measurement\"] =~ /Load_power/)\r\n  |> keep(columns: [\"_time\", \"_value\", \"_measurement\"])",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=", "value": "solar" }
     ]
    }
   ]
  }
 ]
}