#define SECRET_SSID "your_ssid"
#define SECRET_PASS "your_password"
#define SECRET_INFLUXDB_URL "http://10.x.x.x:8086"
#define SECRET_INFLUXDB_TOKEN "your_token"
#define SECRET_INFLUXDB_ORG "default"
#define SECRET_INFLUXDB_BUCKET "your_bucket"
